---
deployment:
  tasks:
    - export DEPLOYPATH=/home/switchsa/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp suppliers.html $DEPLOYPATH
    - /bin/cp energy-deregulation-questions-answers.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R theme $DEPLOYPATH